/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oaup_ocr_imgprocess_image_Preprocess */

#ifndef _Included_net_northking_ocr_imgprocess_image_Preprocess
#define _Included_net_northking_ocr_imgprocess_image_Preprocess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_oaup_ocr_imgprocess_image_Preprocess
 * Method:    detectCornersNative
 * Signature: (Landroid/graphics/Bitmap;Ljava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_com_oaup_ocr_imgprocess_image_Preprocess_detectCornersNative
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_oaup_ocr_imgprocess_image_Preprocess
 * Method:    doPerspectiveNative
 * Signature: (Landroid/graphics/Bitmap;Ljava/util/List;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_oaup_ocr_imgprocess_image_Preprocess_doPerspectiveNative
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_oaup_ocr_imgprocess_image_Preprocess
 * Method:    cvt2GrayNative
 * Signature: (Landroid/graphics/Bitmap;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_oaup_ocr_imgprocess_image_Preprocess_cvt2GrayNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_oaup_ocr_imgprocess_image_Preprocess
 * Method:    cvt2BWNative
 * Signature: (Landroid/graphics/Bitmap;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_oaup_ocr_imgprocess_image_Preprocess_cvt2BWNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_oaup_ocr_imgprocess_image_Preprocess
 * Method:    enhanceNative
 * Signature: (Landroid/graphics/Bitmap;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_oaup_ocr_imgprocess_image_Preprocess_enhanceNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_oaup_ocr_imgprocess_image_Preprocess
 * Method:    setDetectLineParamNative
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_com_oaup_ocr_imgprocess_image_Preprocess_setDetectLineParamNative
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_oaup_ocr_imgprocess_image_Preprocess
 * Method:    detectFrameNative
 * Signature: (Landroid/graphics/Bitmap;)I
 */
JNIEXPORT jint JNICALL Java_com_oaup_ocr_imgprocess_image_Preprocess_detectFrameNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_oaup_ocr_imgprocess_image_Preprocess
 * Method:    detectLinesNative
 * Signature: (Landroid/graphics/Bitmap;Ljava/util/List;Ljava/util/List;)D
 */
JNIEXPORT jdouble JNICALL Java_com_oaup_ocr_imgprocess_image_Preprocess_detectLinesNative
  (JNIEnv *, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
